apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: default
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: colossus-backend
type: Opaque
data:
  S3_AUTH_ACCESS_KEY_ID: YXBw
  S3_AUTH_SECRET_ACCESS_KEY: YXBwMTIzNDU2
