apiVersion: apps/v1
kind: Deployment
metadata:
  name: colossus-alertmanager
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: colossus-alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/instance: colossus-alertmanager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alertmanager
        app.kubernetes.io/instance: colossus-alertmanager
    spec:
      enableServiceLinks: false
      containers:
        - name: alertmanager
          image: "prom/alertmanager:v0.25.0"
          imagePullPolicy: IfNotPresent
          args:
            - "--config.file=/config/alertmanager.yml"
          ports:
            - name: http
              containerPort: 9093
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: alertmanager-config
---
apiVersion: v1
kind: Service
metadata:
  name: colossus-alertmanager
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: colossus-alertmanager
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9093
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: colossus-alertmanager
