---
apiVersion: v1
kind: Service
metadata:
  name: colossus-victoriametrics-headless
  labels:
    app.kubernetes.io/name: victoriametrics
    app.kubernetes.io/instance: colossus-victoriametrics
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 8428
      targetPort: http
      protocol: TCP
    - name: graphite
      port: 2003
      targetPort: graphite
      protocol: TCP
    - name: opentsdb
      port: 4242
      targetPort: opentsdb
      protocol: TCP
    - name: influx
      port: 8089
      targetPort: influx
      protocol: TCP
  selector:
    app.kubernetes.io/name: victoriametrics
    app.kubernetes.io/instance: colossus-victoriametrics

---
apiVersion: v1
kind: Service
metadata:
  name: colossus-victoriametrics
  labels:
    app.kubernetes.io/name: victoriametrics
    app.kubernetes.io/instance: colossus-victoriametrics
    monitoring: "enabled"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8428
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: victoriametrics
    app.kubernetes.io/instance: colossus-victoriametrics
