apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: colossus-victoriametrics
  labels:
    app.kubernetes.io/name: victoriametrics
    app.kubernetes.io/instance: colossus-victoriametrics
spec:
  serviceName: colossus-victoriametrics-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: victoriametrics
      app.kubernetes.io/instance: colossus-victoriametrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: victoriametrics
        app.kubernetes.io/instance: colossus-victoriametrics
        monitoring: "enabled"
    spec:
      enableServiceLinks: false
      containers:
        - name: victoriametrics
          image: "victoriametrics/victoria-metrics:v1.91.2"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8428
              protocol: TCP
            - name: graphite
              containerPort: 2003
              protocol: TCP
            - name: opentsdb
              containerPort: 4242
              protocol: TCP
            - name: influx
              containerPort: 8089
              protocol: TCP
          args:
            - "--storageDataPath=/storage"
            - "--graphiteListenAddr=:2003"
            - "--opentsdbListenAddr=:4242"
            - "--httpListenAddr=:8428"
            - "--influxListenAddr=:8089"
            - "--vmalert.proxyURL=http://colossus-vmalert:8880"
          volumeMounts:
            - name: victoriametrics-data
              mountPath: /storage
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
  volumeClaimTemplates:
    - metadata:
        name: victoriametrics-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: victoriametrics-storage
        resources:
          requests:
            storage: 8Gi
