apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-config
  labels:
    app.kubernetes.io/name: vmagent
    app.kubernetes.io/instance: colossus-vmagent
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s

    # Universal targets config: discover all Services in the namespace
    # that opt-in with label `monitoring=enabled`.
    # Optional service labels:
    # - metrics_path: overrides scrape path (default /metrics)
    # - metrics_scheme: overrides scheme (http/https; default http)
    # The target port must be named one of: http, metrics, api, system
    scrape_configs:
      - job_name: 'kubernetes-services'
        honor_labels: true
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: ['default']
        relabel_configs:
          # Keep only services explicitly enabled for scraping
          - action: keep
            source_labels: [__meta_kubernetes_service_label_monitoring]
            regex: enabled

          # Only keep commonly named metrics ports to avoid scraping random ports
          - action: keep
            source_labels: [__meta_kubernetes_endpoint_port_name]
            regex: (http|metrics|api|system)

          # Set job label from app name for better grouping in dashboards
          - action: replace
            source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
            target_label: job
            regex: (.+)
            replacement: ${1}

          # If custom metrics path provided on the Service via annotation, use it
          - action: replace
            source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            target_label: __metrics_path__
            regex: (.+)
            replacement: ${1}

          # If custom scheme provided on the Service via annotation, use it
          - action: replace
            source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
            target_label: __scheme__
            regex: (.+)
            replacement: ${1}
