apiVersion: apps/v1
kind: Deployment
metadata:
  name: colossus-vmagent
  labels:
    app.kubernetes.io/name: vmagent
    app.kubernetes.io/instance: colossus-vmagent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vmagent
      app.kubernetes.io/instance: colossus-vmagent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vmagent
        app.kubernetes.io/instance: colossus-vmagent
        monitoring: "enabled"
    spec:
      enableServiceLinks: false
      containers:
        - name: vmagent
          image: "victoriametrics/vmagent:v1.91.2"
          imagePullPolicy: IfNotPresent
          args:
            - "--promscrape.config=/etc/prometheus/prometheus.yml"
            - "--remoteWrite.url=http://colossus-victoriametrics:8428/api/v1/write"
            - "--remoteWrite.tmpDataPath=/vmagentdata"
          ports:
            - name: http
              containerPort: 8429
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: data
              mountPath: /vmagentdata
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: vmagent-config
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: colossus-vmagent
  labels:
    app.kubernetes.io/name: vmagent
    app.kubernetes.io/instance: colossus-vmagent
    monitoring: "enabled"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8429
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: vmagent
    app.kubernetes.io/instance: colossus-vmagent
