apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: colossus
  namespace: monitoring
spec:
  selectAllByDefault: true
  remoteWrite:
    - url: "http://vmsingle-colossus.monitoring.svc:8428/api/v1/write"
