---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: colossus
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: colossus
spec:
  configRawYaml: |
    route:
      receiver: blackhole
    receivers:
      - name: blackhole
  podMetadata:
    labels:
      metrics_scrape_enabled: "true"
