apiVersion: v1
kind: ConfigMap
metadata:
  name: vmalert-rules
  labels:
    app.kubernetes.io/name: vmalert
    app.kubernetes.io/instance: colossus-vmalert
data:
  alerts.yml: |
    groups:
      - name: placeholder
        rules:
          - alert: AlwaysZero
            expr: vector(0)
            for: 5m
            labels:
              severity: info
            annotations:
              summary: "Placeholder rule (always zero)"
              description: "This is a placeholder rule to ensure vmalert starts successfully. Replace with real rules when ready."