s3:
  auth:
    endpoint: "${S3_AUTH_ENDPOINT}"
    accessKeyID: "${S3_AUTH_ACCESS_KEY_ID}"
    secretAccessKey: "${S3_AUTH_SECRET_ACCESS_KEY}"
  buckets:
    raw:
      bucketName: "${S3_BUCKETS_RAW_BUCKET_NAME}"
      location: "${S3_BUCKETS_RAW_LOCATION}"
    processed:
      bucketName: "${S3_BUCKETS_PROCESSED_BUCKET_NAME}"
      location: "${S3_BUCKETS_PROCESSED_LOCATION}"

servers:
  system:
    addr: "${SERVERS_SYSTEM_ADDR}"

kafka:
  bootstrap_servers: "${KAFKA_BOOTSTRAP_SERVERS}"
  client_id: "${KAFKA_CLIENT_ID}"
  topic: "${KAFKA_TOPIC}"
  group_id: "${KAFKA_GROUP_ID}"
  session_timeout_ms: "${KAFKA_SESSION_TIMEOUT_MS}"
  auto_offset_reset: "${KAFKA_AUTO_OFFSET_RESET}"
