version: "3"

services:
  s3:
    image: minio/minio
    container_name: "colossus_s3"
    env_file:
      - s3.env
    restart: always
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ${MINIO_DATA_PATH}:/data
