version: "3"

services:
  s3:
    image: minio/minio
    container_name: "colossus_s3"
    env_file:
      - s3.env
    restart: always
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ${MINIO_DATA_PATH}:/data

  backend:
    image: colossus_backend
    container_name: "colossus_backend"
    build:
      context: backend/
      dockerfile: ./Dockerfile
    env_file:
      - backend.env
    restart: always
    command: /backend
    ports:
      - "10001:10001"
      - "20001:20001"
    depends_on:
      - s3
