{
 "title": "Colossus Converter",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,30m,1h" },
   { "name": "job", "query": "colossus-converter" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Successfully processed raw images",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(colossus_converter_processed_images_success{job=\"$job\"}[$__rate_interval])) by (partition)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unsuccessfully processed raw images",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(colossus_converter_processed_images_failures{job=\"$job\"}[$__rate_interval])) by (partition)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate bytes successfully processed of raw images",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(colossus_converter_processed_images_success_bytes{job=\"$job\"}[$__rate_interval])) by (mime_type)",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Total bytes successfully processed of raw images",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(colossus_converter_processed_images_success_bytes{job=\"$job\"}[$__rate_interval]) by (mime_type)",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Go Internals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "process memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"$job\"}",
       "legendFormat": "{{pod}} - resident"
      },
      {
       "expr": "process_virtual_memory_bytes{job=\"$job\"}",
       "legendFormat": "{{pod}} - virtual"
      }
     ]
    },
    {
     "title": "process memory deriv",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(process_resident_memory_bytes{job=\"$job\"}[$interval])",
       "legendFormat": "{{pod}} - resident"
      },
      {
       "expr": "deriv(process_virtual_memory_bytes{job=\"$job\"}[$interval])",
       "legendFormat": "{{pod}} - virtual"
      }
     ]
    },
    {
     "title": "go memstats",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=\"$job\"}",
       "legendFormat": "{{pod}} - bytes allocated"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\"}[30s])",
       "legendFormat": "{{pod}} - alloc rate"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{job=\"$job\"}",
       "legendFormat": "{{pod}} - stack inuse"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"$job\"}",
       "legendFormat": "{{pod}} - heap inuse"
      }
     ]
    },
    {
     "title": "go memstats deriv",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "deriv(go_memstats_alloc_bytes{job=\"$job\"}[$interval])",
       "legendFormat": "{{pod}} - bytes allocated"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\"}[$interval])",
       "legendFormat": "{{pod}} - alloc rate"
      },
      {
       "expr": "deriv(go_memstats_stack_inuse_bytes{job=\"$job\"}[$interval])",
       "legendFormat": "{{pod}} - stack inuse"
      },
      {
       "expr": "deriv(go_memstats_heap_inuse_bytes{job=\"$job\"}[$interval])",
       "legendFormat": "{{pod}} - heap inuse"
      }
     ]
    },
    {
     "title": "open fds",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{job=\"$job\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "open fds deriv",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "deriv(process_open_fds{job=\"$job\"}[$interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=\"$job\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GC duration quantiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=\"$job\"}",
       "legendFormat": "{{pod}}: {{quantile}}"
      }
     ]
    }
   ]
  }
 ]
}