apiVersion: v1
kind: PersistentVolume
metadata:
  name: colossus-grafana-data-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ojgen/.colossus_data_k8s/_grafana_data"
  storageClassName: "grafana-storage"
