apiVersion: v1
kind: PersistentVolume
metadata:
  name: colossus-kafka-data-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ojgen/.colossus_data_k8s/_kafka_data"
  storageClassName: "kafka-storage"
