apiVersion: v1
kind: PersistentVolume
metadata:
  name: colossus-s3-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ojgen/.colossus_data_k8s/_minio_data"
  storageClassName: "s3-storage"
