global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['vmagent:8429']
  - job_name: 'vmalert'
    static_configs:
      - targets: ['vmalert:8880']
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']
  - job_name: 'colossus_backend'
    static_configs:
      - targets: ['colossus_backend:20001']
  - job_name: 'colossus_converter'
    static_configs:
      - targets: ['colossus_converter:20002']
  - job_name: minio-job
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ['s3:9000']
  - job_name: kafka
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['kafka-minion:8080']
