apiVersion: apps/v1
kind: Deployment
metadata:
  name: colossus-backend
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: colossus-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
      app.kubernetes.io/instance: colossus-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
        app.kubernetes.io/instance: colossus-backend
    spec:
      containers:
      - name: backend
        image: "ojgen/colossus-backend:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - name: main
          containerPort: 10001
          protocol: TCP
        - name: system
          containerPort: 20001
          protocol: TCP
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret
        livenessProbe:
          httpGet:
            path: /healthz
            port: main
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: main
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
      restartPolicy: Always