s3:
  auth:
    endpoint: "${S3_AUTH_ENDPOINT}"
    accessKeyID: "${S3_AUTH_ACCESS_KEY_ID}"
    secretAccessKey: "${S3_AUTH_SECRET_ACCESS_KEY}"
  buckets:
    raw:
      bucketName: "${S3_BUCKETS_RAW_BUCKET_NAME}"
      location: "${S3_BUCKETS_RAW_LOCATION}"
    processed:
      bucketName: "${S3_BUCKETS_PROCESSED_BUCKET_NAME}"
      location: "${S3_BUCKETS_PROCESSED_LOCATION}"
