---
apiVersion: v1
kind: Service
metadata:
  name: colossus-kafka-headless
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: colossus-kafka
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 29092
      targetPort: kafka
      protocol: TCP
      name: kafka
    - port: 9093
      targetPort: controller
      protocol: TCP
      name: controller
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: colossus-kafka

---
apiVersion: v1
kind: Service
metadata:
  name: colossus-kafka
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: colossus-kafka
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: kafka
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: colossus-kafka
